### ISSUE TITLE
invalid model generated from #2849

### ISSUE THREAD

**Issue by NikolajBjorner** [levnach/z3#111]
```
(set-option :model_validate true)
(set-option :smt.arith.solver 6)
(set-option :lp.nla true)

(declare-fun c () Real)
(declare-fun b () Real)
(declare-fun a () Real)
(declare-fun i () Int)
(assert (< (+ (- (- a) b) c) 0.0))
(assert (< (- (- a b) c) 0.0))
(assert (< (+ a b c (* (to_real i) c)) 0.0))
(check-sat)

```

**Comment by levnach** [comment]
It does not generate an invalid model anymore. From the other side it does not find a solution, while the problem is sat. One can, for example add (assert (= i 0))
and get 
(model 
  (define-fun c () Real
    (- (/ 1.0 2.0)))
  (define-fun a () Real
    (- (/ 1.0 2.0)))
  (define-fun b () Real
    (/ 1.0 2.0))
  (define-fun i () Int
    0)
)
Seems a tactic is missing.
